language: node_js
node_js: "8"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
before_script:
  - mkdir dist
  - mkdir dist/styles
script:
  - yarn build_slider
  - cp -a slider/styles/. dist/styles
  - yarn build_docs
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: .docz/dist
  - provider: npm
    email: "mutatedbread@gmail.com"
    api_key: $NPM_TOKEN
  on:
    branch: release
